### ISSUE TITLE
python-lrcalc says its 2.1 but has 2.0 bundled

### ISSUE THREAD

**Issue by tobiasdiez** [conda-forge/lrcalc-feedstock#12]
It's a bit of an easter egg, but sadly an unwanted one. The files from https://anaconda.org/conda-forge/python-lrcalc/files (e.g. `python-lrcalc-2.1-py310h7a76584_4` say they bundle version 2.1, but if you look under `lib\python3.10\site-packages` they actually contain version 2.0 (at least `lrcalc-2.0.0.dist-info`, not sure which version is the `so` file).

**Comment by isuruf** [comment]
lrcalc 2.1 didn't update the version number in setup.py.
